apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongobackend
  labels:
    app.kubernetes.io/name: mongobackend
    app.kubernetes.io/component: backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mongobackend
      app.kubernetes.io/component: backend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mongobackend
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: mongobackend
        image: mongo:4.2
        volumeMounts:
        - mountPath: /backend
          name: mongo-pvc
        args:
          - --bind_ip
          - 0.0.0.0
        ports:
        - containerPort: 27017
      volumes:
        - name: mongo-pvc
          persistentVolumeClaim:
            claimName: mongo-pvc-hostpath